name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.0.x
      - name: Publish
        run: dotnet publish ./TheMagnificent11.Site/TheMagnificent11.Site.csproj -c Release -o ./release
      - name: Change base-tag in index.html
        run: sed -i 's/<base href="\/" \/>/<base href="\/TheMagnificent11\/" \/>/g' release/wwwroot/index.html
      - name: Add .nojekyll file
        run: touch release/wwwroot/.nojekyll
      - name: Commit wwwroot to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3.6.1
        with:
          github_token: ${{ secrets.PUBLISH_TOKEN }}
          publish_branch: gh-pages
          publish_dir: release/wwwroot
          allow_empty_commit: false
          keep_files: false
          force_orphan: true
